title: VRL`s YOLOL archive
description: May the free YOLOL bring you closer to great venturing challanges with more safety than others!
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
